[Ether]
addr = "wss://rinkeby.infura.io/ws/v3/43b36e4162f04775b91869b9fed5e5c8"
name = "SmartContractTester"
contract_address = "0xD3880ea40670eD51C3e3C0ea089fDbDc9e3FBBb4"
abi_path = "broker.abi"
key_path = "account.key"
password = "password"