[Ether]
addr = "wss://rinkeby.infura.io/ws/v3/731722c66a504aa6bcc25135f3dfc3f9"
name = "SecondEthereum"
contract_address = "0xD3880ea40670eD51C3e3C0ea089fDbDc9e3FBBb4"
abi_path = "broker.abi"
key_path = "account.key"
password = "password"